:: Only way for Windooooooows to show correct timestamps without ruining my logfile names...
:: Windows, go back to the corner and think at what you push me to do...
for /f "skip=1" %%x in ('wmic os get localdatetime') do if not defined mydate set mydate=%%x
server.exe -batchmode -logFile serverlog%mydate%.log